### ISSUE TITLE
sensor data unreliable

### ISSUE THREAD

**Issue by aoaaron** [binarylogic/trinnov-altitude-homeassistant#4]
Hi mate.. trinnov sensor data on this is so unreliable. sometimes comes up, sometimes doesnt! any fix for it>

**Comment by aoaaron** [comment]
if i restart home assistant the sensor data comes back... so seems to be a HA issue rather than trinnov issue.

**Comment by binarylogic** [comment]
Hm, I'll see if I can reproduce. Keep in mind, the Altitude needs to be on for sensor data to be available. Reopen if you experience it again.
